# First Notebook to use

This notebook scrapes the page letterboxd for my own personal rating of movies, plus the homepage of the reviewed movies.

I have reviewed the https://letterboxd.com/robots.txt file, and those pages are all allowed.

In [40]:
import requests
from bs4 import BeautifulSoup
import time
import pandas as pd
import numpy as np
import time

In [41]:
BASE_URL = "https://letterboxd.com"
PROFILE_URL = "https://letterboxd.com/bronzemarkian/films/"

headers = {"User-Agent": "Mozilla/5.0"}

# Step 1: Get all movie links from your profile page
r = requests.get(PROFILE_URL, headers=headers)
soup = BeautifulSoup(r.text, "html.parser")
r.status_code # 200 means everything okay

200

In [42]:
# Loop over each available page

page = 1
all_movies = []
while True:
    url = f'{PROFILE_URL}page/{page}/'
    resp = requests.get(url, headers=headers)
    if resp.status_code != 200:
        break
    soup = BeautifulSoup(resp.text, "html.parser")
    movies = soup.find_all('li', class_='griditem') # from inspecting page, 'griditem' is the class holding info about each movie
    if not movies: # this is what breaks when it tries page 3 and there are no movies there
        break
    all_movies += movies
    page += 1

In [43]:
def stars_to_number(stars): # to get actual rating numbers
    if stars:
        num_stars = stars.count('★')
        half_star = stars.count('½')
        return num_stars + 0.5*half_star
    else:
        return None
    
def find_features_from_link(movie_link):
    resp = requests.get(movie_link, headers=headers)
    soup = BeautifulSoup(resp.text, "html.parser")
    avg_rating = float(soup.find_all("meta", attrs={"name": "twitter:data2"})[0]["content"].split(' ')[0])
    movie_genres = [a.text.strip() for a in soup.select('a.text-slug[href^="/films/genre/"]')]
    movie_director = soup.find_all("meta", attrs={"name": "twitter:data1"})[0]["content"]
    movie_countries = [a.text.strip() for a in soup.select('a.text-slug[href^="/films/country/"]')]  
    movie_languages = [a.text.strip() for a in soup.select('a.text-slug[href^="/films/language/"]')]

    return avg_rating, movie_genres, movie_director, movie_countries, movie_languages

    
titles = []
years = []
personal_ratings = []
links = []

for movie in all_movies:
    # The title and link are in the 'data-item-name' and 'data-item-link' attributes of the div
    div = movie.find('div', class_='react-component')
    title_year = div['data-item-name']
    movie_link = "https://letterboxd.com" + div['data-item-link']
    
    rating_tag = movie.find('span', class_='rating')
    personal_movie_rating = rating_tag.text if rating_tag else None

    movie_title = title_year.split("(")[0][:-1]
    movie_year = int(title_year.split("(")[1].replace(")", ""))
    
    titles.append(movie_title)
    years.append(movie_year)
    personal_ratings.append(stars_to_number(personal_movie_rating))
    links.append(movie_link)
    # print(title, rating, stars_to_number(rating), link)

avg_ratings = []
genres = []
directors = []
countries = []
languages = []

for link in links:
    
    avg_rating, genre, director, country, language = find_features_from_link(link)
    avg_ratings.append(avg_rating)
    genres.append(genre)
    directors.append(director)
    countries.append(country)
    languages.append(language)
    time.sleep(1)  # dont hammer server and risk getting blocked

In [44]:
rows = []

for i in range(len(titles)):
    rows.append({
        "title": titles[i],
        "release_year": years[i],
        "personal_rating": personal_ratings[i],
        "avg_rating": avg_ratings[i],
        "genre": genres[i],
        "director": directors[i],
        "country": countries[i],
        "language": languages[i]
    })
    df = pd.DataFrame(rows)

In [45]:
import re
def seperate_directors(s):
    if not s:
        return []
    if type(s) != str:
        return s

    s = re.sub(r'\bet\s+al\.?\b', '', s, flags=re.IGNORECASE)
    s = re.sub(r',\s*,', ',', s)
    s = s.strip(' ,')   # removes trailing whitespace and/or commas

    return [d.strip() for d in s.split(',') if d.strip()]

In [49]:
df2 = df[:]
df2['director'] = df2['director'].apply(seperate_directors)

In [50]:
# df.to_csv('initial_df.csv', index=False)
df2.to_csv('initial_dframe.csv', index=False)

Encoding below is done later so not used here.

In [12]:
import ast

cat_features = ['genre', 'country', 'language']

df = pd.read_csv('initial_df.csv')
for column in cat_features:
    df[column] = df[column].apply(lambda x: ast.literal_eval(x))

In [13]:
# Now the dataframe is mostly done, but there are a lot of categorical features, with multiple inputs too. I want to encode them.

from sklearn.preprocessing import MultiLabelBinarizer

def encode_category(dframe, column_name, name_of_new_column):

    mlb = MultiLabelBinarizer()
    column_encoded = mlb.fit_transform(dframe[column_name])
    new_dframe = pd.DataFrame(column_encoded, columns=[f"{column_name}: {g}" for g in mlb.classes_], index=dframe.index)
    # columns=[f"Genre: {g}" for g in mlb.classes_], 
    new_dframe[name_of_new_column] = 0

    for category in new_dframe.columns:
        if new_dframe[category].sum() < 2: # if rare category
            new_dframe[name_of_new_column] = new_dframe[name_of_new_column] | new_dframe[category] # 1 in same row if 1 already in new column or 1 in category, else 0
            new_dframe = new_dframe.drop(category, axis=1) # drop the rare category
    
    dframe = dframe.drop(column_name, axis=1)

    return pd.concat([dframe, new_dframe], axis=1)

In [11]:
print(type(df['genre'].iloc[0]))

<class 'list'>

In [16]:
df_encoded = df[:]
for column in cat_features:
    df_encoded = encode_category(df_encoded, column, f'rare {column}')
df_encoded.head(10)

,title,release_year,personal_rating,avg_rating,director,genre: Action,genre: Adventure,genre: Animation,genre: Comedy,genre: Crime,...,language: Italian,language: Japanese,language: Latin,language: Portuguese,language: Russian,language: Spanish,language: Swedish,language: Urdu,language: Xhosa,rare language
0,Oppenheimer,2023,4.5,4.17,Christopher Nolan,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
1,Spider-Man: Across the Spider-Verse,2023,5.0,4.41,"Kemp Powers, Justin K. Thompson et al",1,1,1,0,0,...,1,0,0,0,0,1,0,0,0,0
2,The Super Mario Bros. Movie,2023,4.0,3.22,"Aaron Horvath, Michael Jelenic",0,1,1,1,0,...,0,0,0,0,0,0,0,0,0,0
3,Avatar: The Way of Water,2022,3.0,3.62,James Cameron,1,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,Jujutsu Kaisen 0,2021,4.0,3.93,Sunghoo Park,1,0,1,0,0,...,0,1,0,0,0,0,0,0,0,0
5,Spider-Man: No Way Home,2021,4.0,3.83,Jon Watts,1,1,0,0,0,...,0,0,0,0,0,0,0,0,0,1
6,No Time to Die,2021,3.0,3.52,Cary Joji Fukunaga,1,1,0,0,0,...,1,0,0,0,1,1,0,0,0,0
7,Dune,2021,3.5,3.88,Denis Villeneuve,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
8,JUJUTSU KAISEN,2020,3.5,4.22,"Yui Umemoto, Ryohei Takeshita et al",0,0,1,0,0,...,0,1,0,0,0,0,0,0,0,0
9,Another Round,2020,4.0,4.09,Thomas Vinterberg,0,0,0,1,0,...,0,0,0,0,0,0,1,0,0,0

# Below this is testing

In [161]:
# Now the dataframe is mostly done, but there are a lot of categorical features, with multiple inputs too. I want to encode them.

from sklearn.preprocessing import MultiLabelBinarizer

mlb = MultiLabelBinarizer()
genre_encoded = mlb.fit_transform(df['genres'])

genre_df = pd.DataFrame(genre_encoded, columns=[f"Genre: {g}" for g in mlb.classes_], index=df.index)

genre_df['New Genre'] = 0

for genre in genre_df.columns:
    if genre_df[genre].sum() < 2: # rare genre, so want a 1 in new genre in the same row
        print(genre)
        genre_df['New Genre'] = genre_df['New Genre'] | genre_df[genre] # 1 in same row is 1 already in new genre column or genre column, else 0
        genre_df = genre_df.drop(genre, axis = 1)

genre_df.head()

Genre: Music
Genre: Western

,Genre: Action,Genre: Adventure,Genre: Animation,Genre: Comedy,Genre: Crime,Genre: Drama,Genre: Family,Genre: Fantasy,Genre: History,Genre: Horror,Genre: Mystery,Genre: Romance,Genre: Science Fiction,Genre: Thriller,Genre: War,New Genre
0,0,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0
1,1,1,1,0,0,0,0,0,0,0,0,0,1,0,0,0
2,0,1,1,1,0,0,1,1,0,0,0,0,0,0,0,0
3,1,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0
4,1,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0

In [154]:
for genre in genre_df.columns:
    print(genre_df[genre].sum(), genre)

58 Action
58 Adventure
17 Animation
17 Comedy
16 Crime
38 Drama
15 Family
21 Fantasy
2 History
4 Horror
2 Mystery
3 Romance
43 Science Fiction
26 Thriller
3 War
2 New Genre

In [141]:
genre_df['New Genre'].sum()

np.int64(0)

In [ ]:
genre_df.columns[0]

'Action'

In [4]:
def stars_to_number(stars): # to get actual rating numbers
    if stars:
        num_stars = stars.count('★')
        half_star = stars.count('½')
        return num_stars + 0.5*half_star
    else:
        return None

In [89]:
titles = []
ratings = []
links = []

for movie in all_movies:
    # The title and link are in the 'data-item-name' and 'data-item-link' attributes of the div
    div = movie.find('div', class_='react-component')
    title_year = div['data-item-name']
    link = "https://letterboxd.com" + div['data-item-link']
    
    rating_tag = movie.find('span', class_='rating')
    rating = rating_tag.text if rating_tag else None

    title = title_year.split("(")[0][:-1]
    year = int(title_year.split("(")[1].replace(")", ""))

    titles.append(title)
    ratings.append(rating)
    links.append(link)
    # print(title, rating, stars_to_number(rating), link)
    print(title)

Oppenheimer
Spider-Man: Across the Spider-Verse
The Super Mario Bros. Movie
Avatar: The Way of Water
Jujutsu Kaisen 0
Spider-Man: No Way Home
No Time to Die
Dune
JUJUTSU KAISEN
Another Round
Tenet
Joker
Avengers: Endgame
Checkered Ninja
Spider-Man: Into the Spider-Verse
The Meg
Avengers: Infinity War
Star Wars: The Last Jedi
Blade Runner 2049
Dunkirk
Logan
Moana
Warcraft
The Conjuring 2
Deadpool
Star Wars: The Force Awakens
Spectre
The Martian
Avengers: Age of Ultron
Interstellar
Transformers: Age of Extinction
Edge of Tomorrow
Boyhood
Whiplash
The Wolf of Wall Street
Frozen
The Conjuring
The Great Gatsby
Django Unchained
Skyfall
The Dark Knight Rises
The Avengers
The Intouchables
Harry Potter and the Deathly Hallows: Part 2
Transformers: Dark of the Moon
Fast Five
Harry Potter and the Deathly Hallows: Part 1
The Social Network
Inception
How to Train Your Dragon
Avatar
2012
Harry Potter and the Half-Blood Prince
Transformers: Revenge of the Fallen
Inglourious Basterds
Fast & Furious
The Little Mermaid: Ariel's Beginning
The Dark Knight
WALL·E
Iron Man
Taken
The Bucket List
I Am Legend
Harry Potter and the Order of the Phoenix
Transformers
Ratatouille
Casino Royale
The Prestige
The Departed
The Fast and the Furious: Tokyo Drift
V for Vendetta
King Kong
Harry Potter and the Goblet of Fire
Batman Begins
Star Wars: Episode III – Revenge of the Sith
Harry Potter and the Prisoner of Azkaban
The Lord of the Rings: The Return of the King
2 Fast 2 Furious
Finding Nemo
The Lord of the Rings: The Two Towers
Harry Potter and the Chamber of Secrets
Star Wars: Episode II – Attack of the Clones
Spider-Man
The Lord of the Rings: The Fellowship of the Ring
Harry Potter and the Philosopher's Stone
Monsters, Inc.
Planet of the Apes
The Fast and the Furious
Shrek
Flickering Lights
Memento
Gladiator
American Psycho
Fight Club
American Beauty
Star Wars: Episode I – The Phantom Menace
The Matrix
Saving Private Ryan
The Truman Show
Titanic
The Shawshank Redemption
Forrest Gump
The Lion King
Home Alone 2: Lost in New York
Terminator 2: Judgment Day
Home Alone
The Land Before Time
Die Hard
Back to the Future
The Terminator
Return of the Jedi
E.T. the Extra-Terrestrial
The Empire Strikes Back
Star Wars
The Godfather Part II
The Godfather

In [8]:
len(links)

116

In [25]:
links[0]

'https://letterboxd.com/film/oppenheimer-2023/genres/'

In [83]:
resp2 = requests.get(links[0], headers=headers)
soup_link = BeautifulSoup(resp2.text, "html.parser")
resp2.status_code

200

In [68]:
soup_link

<!DOCTYPE html>

<html class="context-client-unknown no-mobile no-js" id="html" lang="en">
<head>
<meta charset="utf-8"/>
<meta content="width=1024" name="viewport"/>
<meta content="IE=edge,chrome=1" http-equiv="X-UA-Compatible"/>
<meta content="The story of J. Robert Oppenheimer's role in the development of the atomic bomb during World War II." name="description"/>
<meta content="video.movie" property="og:type"/>
<meta content="https://letterboxd.com/film/oppenheimer-2023/genres/" property="og:url"/>
<meta content="Oppenheimer (2023)" property="og:title"/>
<meta content="The story of J. Robert Oppenheimer's role in the development of the atomic bomb during World War II." property="og:description"/>
<meta content="https://a.ltrbxd.com/resized/sm/upload/mn/uu/op/02/oppenheimer-2023-1200-1200-675-675-crop-000000.jpg?v=aa1b3a6d85" property="og:image"/><meta content="1200" property="og:image:width"/><meta content="675" property="og:image:height"/>
<meta content="173683136069040" property="fb:app_id"/>
<meta content="summary_large_image" name="twitter:card"/>
<meta content="@letterboxd" name="twitter:site"/><meta content="https://letterboxd.com/film/oppenheimer-2023/genres/" name="twitter:url"/>
<meta content="Oppenheimer (2023)" name="twitter:title"/>
<meta content="The story of J. Robert Oppenheimer's role in the development of the atomic bomb during World War II." name="twitter:description"/>
<meta content="Directed by" name="twitter:label1"/><meta content="Christopher Nolan" name="twitter:data1"/>
<meta content="Average rating" name="twitter:label2"/><meta content="4.17 out of 5" name="twitter:data2"/>
<meta content="https://a.ltrbxd.com/resized/sm/upload/mn/uu/op/02/oppenheimer-2023-1200-1200-675-675-crop-000000.jpg?v=aa1b3a6d85" name="twitter:image"/>
<meta content="Letterboxd" name="application-name"/>
<meta content="#14181C" name="theme-color"/>
<meta content="#445566" name="msapplication-TileColor"/>
<meta content="app-id=1054271011, affiliate-data=11l5KW, app-argument=https://letterboxd.com/film/oppenheimer-2023/genres/" name="apple-itunes-app"/>
<meta content="yes" name="mobile-web-app-capable"/>
<title>‎Oppenheimer (2023) directed by Christopher Nolan • Reviews, film + cast • Letterboxd</title>
<script>

		((r, n) => {
			r.dataset.useragent = n.userAgent
			r.dataset.platform = n.platform
		})(document.documentElement, navigator)

		var isMobile = false,
			isMobileOptimised = true,
			renderMobile = false,
			useStaticFonts = false,
			disableFrameProtection = false,
			baseURL = '',
			staticAssetBaseURL = 'https://s.ltrbxd.com/'.slice(0, -1),
			successMessages = [],
			errorMessages = [],
			stickyMessages = [],
			globals = {
			autoAddFilm: false
				, spinners: {
					ajax_242d35: 'https://s.ltrbxd.com/static/img/spinner-dark-2x-BA9SNVrD.gif',
					spinner_12_2C3641: 'https://s.ltrbxd.com/static/img/spinner-dark-2x-BA9SNVrD.gif',
					spinner_14_20272f: 'https://s.ltrbxd.com/static/img/spinner-dark-2x-BA9SNVrD.gif',
					spinner_16_161B21: 'https://s.ltrbxd.com/static/img/spinner-dark-2x-BA9SNVrD.gif'
				}
			},
			supermodelCSRF = "",
			gRecaptchaKey = '6Le3mMIUAAAAAEXbwZ7M1R5jEv0V5xbvj7bgXq2g',
			geolocation = {
				country: ""
			},
			person = {
				username: ""
				, loggedIn: false

				, showAds: true
				, role: "guest"
				, hasExtendedServiceFilters: false
				, canBulkAddToLists: false
				, canFilterOwned: false
				, hasHqRole: false
				, canHaveHqDashboard: false
				, hasMemberStatistics: false
				, blockedMembers: []
				, showAdultContent: false
				, validated: null
				, trusted: false
				, hasBlocked : function(member) { for (var i = 0; i !== person.blockedMembers.length; i++) {if (person.blockedMembers[i] === member) return true;} return false; }
				, viewingTags: []
				, hasMoreTags: true
				, getCustomPoster : function(uid) { return null; }
				, getCustomBackdrop : function(uid) { return null; }
			},
			disableAds = false,
			analytic_params = {};


supermodelCSRF = '09173b9d5bd9d70f7f9b'; geolocation.country = 'DK'; analytic_params['user_type'] = 'Visitor';

	</script>
<script>
		window.dataLayer = window.dataLayer || [];
		window.gtag = window.gtag || function () {
			dataLayer.push(arguments);
		};
		function ga() {}
	</script>
<script async="" src="https://www.googletagmanager.com/gtag/js?id=G-D3ECBB4D7L"></script>
<script>
		window.dataLayer = window.dataLayer || [];
		window.gtag = window.gtag || function () {
			dataLayer.push(arguments);
		};
		gtag('js', new Date());

		analytic_params['template'] = '/object/film';


				analytic_params['film_id'] = 'wUow';


		if (analytic_params.member_type) {
			gtag('set', 'user_properties', {
				member_type: analytic_params.member_type,
			});
			delete analytic_params.member_type;
		}
		var config = {
			...analytic_params,
			'cookie_domain': 'letterboxd.com',
			'optimize_id': 'GTM-TB8HSDN',
		};
		gtag('config', 'G-D3ECBB4D7L', config);
	</script>
<script>
function ASAP(callback) {
	if (window.__ASAPPED) {
		callback()
		return
	}
	if (!window.__ASAP) {
		window.__ASAP = []
	}
	window.__ASAP.push(callback)
}
</script>
<script>











			  function setUseMobileSiteCookie(useMobile) {
					const value = useMobile ? 'yes' : 'no'
					const date = new Date()
					const maxAge = 365 * 24 * 60 * 60
					date.setTime(date.getTime() + maxAge * 1000)
					const expires = '; expires=' + date.toUTCString()
					const cookieValuePair = 'useMobileSite=' + value
					document.cookie = cookieValuePair + expires + '; path=/; maxAge=' + maxAge

					if (document.cookie.includes(cookieValuePair)) {
						window.location.reload(true)
					} else {
						console.error('Failed to set useMobileSite cookie.')
					}
				}

				/*
				 * If ?fromApp=true, it's possible for user is already in the correct mode, so only try
				 * reloading if that's the case. In fact, trying to reload the page regardless causes an
				 * infinite loop as the ?fromApp=true parameter is always present.
				 */
				const isMobileWidth = screen.width < 768
				if (isMobileWidth && !document.cookie.includes('useMobileSite=yes')) {
					setUseMobileSiteCookie(true)
				} else if (!isMobileWidth && !document.cookie.includes('useMobileSite=no')) {
					setUseMobileSiteCookie(false)
				}


	</script>
<script type="text/javascript"> (function(data) { data.viewingable = data.viewingable || {}; data.viewingable.uid = 'film:784328'; data.viewingable.type = 'film'; data.viewingable.dataEndpoint = '/film/oppenheimer-2023/json/'; })(window.__BXD_DATA = window.__BXD_DATA || {}) </script>
<script>
		window.ramp = window.ramp || {};
		window.ramp.que = window.ramp.que || [];
		window.ramp.passiveMode = false;
		window.ramp.forcePath = '';
		window.ramp.custom_tags = [
			'drama',
			'history',
			'intl_false',
			'wUow',
			'',
			''
		];
	</script>
<script src="//cdn.intergient.com/1024338/72804/ramp_config.js"></script>
<script>
		window._pwGA4PageviewId = ''.concat(Date.now());
		window.dataLayer = window.dataLayer || [];
		window.gtag = window.gtag || function () {
			dataLayer.push(arguments);
		};
		gtag('js', new Date());
		gtag('config', 'G-L0W7RDZXX3', { 'send_page_view': false });
		gtag(
			'event',
			'ramp_js',
			{
				'send_to': 'G-L0W7RDZXX3',
				'pageview_id': window._pwGA4PageviewId
			}
		);

		(function() {
			const userAgent = navigator.userAgent || navigator.vendor || window.opera;
			window.isAndroid = new RegExp("android", "i").test(userAgent);
			window.isIOS = new RegExp("iPad|iPhone|iPod", "i").test(userAgent) && !window.MSStream;
			window.adsLocation = 'DK';
		})();
	</script>
<link href="/manifest.json" rel="manifest"/>
<link href="/humans.txt" rel="author" type="text/plain"/>
<link color="#445566" href="https://s.ltrbxd.com/static/img/letterboxd-decal-l-16px-DorUFlWn.svg" rel="mask-icon"/>
<link href="https://s.ltrbxd.com/static/img/touch-icon-192x192-lO1g3Ot4.png" rel="shortcut icon" sizes="196x196"/>
<link href="/apple-touch-icon.png" rel="apple-touch-icon"/>
<link href="/favicon.ico" rel="shortcut icon"/>
<link href="/static/opensearch.xml" rel="search" title="Letterboxd" type="application/opensearchdescription+xml"/>
<script crossorigin="" src="https://s.ltrbxd.com/static/js/es/js/app-detection-B6-GztkV.js" type="module"></script>
<link crossorigin="" href="https://s.ltrbxd.com/static/js/es/chunks/B5Qt9EMX.js" rel="modulepreload"/>
<link crossorigin="" href="https://s.ltrbxd.com/static/js/es/chunks/Duz0x7wZ.js" rel="modulepreload"/>
<script type="module">import.meta.url;import("_").catch(()=>1);(async function*(){})().next();if(location.protocol!="file:"){window.__vite_is_modern_browser=true}</script>
<script type="module">!function(){if(window.__vite_is_modern_browser)return;console.warn("vite: loading legacy chunks, syntax error above and the same error below should be ignored");var e=document.getElementById("vite-legacy-polyfill"),n=document.createElement("script");n.src=e.src,n.onload=function(){System.import(document.getElementById('vite-legacy-entry').getAttribute('data-src'))},document.body.appendChild(n)}();</script>
<script crossorigin="" src="https://s.ltrbxd.com/static/js/es/main-i39z62rq.js" type="module"></script>
<link crossorigin="" href="https://s.ltrbxd.com/static/js/es/chunks/B5Qt9EMX.js" rel="modulepreload"/>
<link crossorigin="" href="https://s.ltrbxd.com/static/js/es/chunks/BCTBTwm7.js" rel="modulepreload"/>
<link crossorigin="" href="https://s.ltrbxd.com/static/js/es/chunks/D6-XlEtG.js" rel="modulepreload"/>
<link crossorigin="" href="https://s.ltrbxd.com/static/js/es/chunks/B7pRgGH2.js" rel="modulepreload"/>
<link crossorigin="" href="https://s.ltrbxd.com/static/js/es/chunks/DpSFKnps.js" rel="modulepreload"/>
<link crossorigin="" href="https://s.ltrbxd.com/static/js/es/chunks/03U_i1H8.js" rel="modulepreload"/>
<link crossorigin="" href="https://s.ltrbxd.com/static/js/es/chunks/BKjBsywS.js" rel="modulepreload"/>
<link crossorigin="" href="https://s.ltrbxd.com/static/js/es/chunks/DiOw5U6i.js" rel="modulepreload"/>
<link crossorigin="" href="https://s.ltrbxd.com/static/js/es/chunks/Dxzbedgu.js" rel="modulepreload"/>
<link crossorigin="" href="https://s.ltrbxd.com/static/js/es/chunks/D4jkuF44.js" rel="modulepreload"/>
<link crossorigin="" href="https://s.ltrbxd.com/static/js/es/chunks/ChpbvBPH.js" rel="modulepreload"/>
<link crossorigin="" href="https://s.ltrbxd.com/static/js/es/chunks/CF6vd0R2.js" rel="modulepreload"/>
<link crossorigin="" href="https://s.ltrbxd.com/static/js/es/chunks/BLpqPwTf.js" rel="modulepreload"/>
<link crossorigin="" href="https://s.ltrbxd.com/static/js/es/chunks/C3Ay1Ke8.js" rel="modulepreload"/>
<link crossorigin="" href="https://s.ltrbxd.com/static/js/es/chunks/CkhgB9_0.js" rel="modulepreload"/>
<link crossorigin="" href="https://s.ltrbxd.com/static/js/es/chunks/qt9y7WI1.js" rel="modulepreload"/>
<link crossorigin="" href="https://s.ltrbxd.com/static/js/es/chunks/CswyOWBu.js" rel="modulepreload"/>
<link crossorigin="" href="https://s.ltrbxd.com/static/js/es/chunks/GVR8ng7U.js" rel="modulepreload"/>
<link crossorigin="" href="https://s.ltrbxd.com/static/js/es/chunks/Dw1UnyvJ.js" rel="modulepreload"/>
<link crossorigin="" href="https://s.ltrbxd.com/static/js/es/chunks/BeurgYGG.js" rel="modulepreload"/>
<link crossorigin="" href="https://s.ltrbxd.com/static/js/es/chunks/CUcMfv5U.js" rel="modulepreload"/>
<link crossorigin="" href="https://s.ltrbxd.com/static/js/es/chunks/CbXmRM-a.js" rel="modulepreload"/>
<link crossorigin="" href="https://s.ltrbxd.com/static/js/es/chunks/DSY2fS8P.js" rel="modulepreload"/>
<link crossorigin="" href="https://s.ltrbxd.com/static/js/es/chunks/Id4iG9uS.js" rel="modulepreload"/>
<link crossorigin="" href="https://s.ltrbxd.com/static/js/es/chunks/C3e4t58V.js" rel="modulepreload"/>
<link crossorigin="" href="https://s.ltrbxd.com/static/js/es/chunks/BOYOeiUI.js" rel="modulepreload"/>
<link crossorigin="" href="https://s.ltrbxd.com/static/js/es/chunks/AZAFc45w.js" rel="modulepreload"/>
<link crossorigin="" href="https://s.ltrbxd.com/static/js/es/chunks/DbkyL-rk.js" rel="modulepreload"/>
<link crossorigin="" href="https://s.ltrbxd.com/static/js/es/chunks/D4Yk99Ne.js" rel="modulepreload"/>
<link crossorigin="" href="https://s.ltrbxd.com/static/js/es/chunks/CCPv9W2X.js" rel="modulepreload"/>
<link crossorigin="" href="https://s.ltrbxd.com/static/js/es/chunks/DOHxIiFh.js" rel="modulepreload"/>
<link crossorigin="" href="https://s.ltrbxd.com/static/js/es/chunks/DPeCBLXW.js" rel="modulepreload"/>
<link crossorigin="" href="https://s.ltrbxd.com/static/js/es/chunks/CBHMxBpJ.js" rel="modulepreload"/>
<link crossorigin="" href="https://s.ltrbxd.com/static/js/es/chunks/CMMPhZm8.js" rel="modulepreload"/>
<link crossorigin="" href="https://s.ltrbxd.com/static/js/es/chunks/Bbh8MmKk.js" rel="modulepreload"/>
<link crossorigin="" href="https://s.ltrbxd.com/static/js/es/chunks/Ban4G7ML.js" rel="modulepreload"/>
<link crossorigin="" href="https://s.ltrbxd.com/static/js/es/chunks/_RochNgE.js" rel="modulepreload"/>
<link crossorigin="" href="https://s.ltrbxd.com/static/js/es/chunks/-rqf-nHv.js" rel="modulepreload"/>
<link crossorigin="" href="https://s.ltrbxd.com/static/js/es/chunks/hzgQj22F.js" rel="modulepreload"/>
<link crossorigin="" href="https://s.ltrbxd.com/static/js/es/chunks/Cr3O1wMX.js" rel="modulepreload"/>
<link crossorigin="" href="https://s.ltrbxd.com/static/js/es/chunks/E09ShL52.js" rel="modulepreload"/>
<link crossorigin="" href="https://s.ltrbxd.com/static/js/es/chunks/DurStC4r.js" rel="modulepreload"/>
<link crossorigin="" href="https://s.ltrbxd.com/static/js/es/chunks/MRfd4lNX.js" rel="modulepreload"/>
<link crossorigin="" href="https://s.ltrbxd.com/static/js/es/chunks/DZEHBdoo.js" rel="modulepreload"/>
<link crossorigin="" href="https://s.ltrbxd.com/static/js/es/chunks/CqkxH0ZD.js" rel="modulepreload"/>
<link crossorigin="" href="https://s.ltrbxd.com/static/js/es/chunks/Duz0x7wZ.js" rel="modulepreload"/>
<link crossorigin="" href="https://s.ltrbxd.com/static/js/es/chunks/bKpgursT.js" rel="modulepreload"/>
<link crossorigin="" href="https://s.ltrbxd.com/static/js/es/chunks/BGVqBqED.js" rel="modulepreload"/>
<link crossorigin="" href="https://s.ltrbxd.com/static/js/es/chunks/CP0EPuP8.js" rel="modulepreload"/>
<link crossorigin="" href="https://s.ltrbxd.com/static/js/es/chunks/qdU7E-mG.js" rel="modulepreload"/>
<link crossorigin="" href="https://s.ltrbxd.com/static/js/es/chunks/CYQg_BNx.js" rel="modulepreload"/>
<link crossorigin="" href="https://s.ltrbxd.com/static/js/es/chunks/nV9Wew8p.js" rel="modulepreload"/>
<link crossorigin="" href="https://s.ltrbxd.com/static/js/es/chunks/CF74jhiq.js" rel="modulepreload"/>
<link crossorigin="" href="https://s.ltrbxd.com/static/js/es/chunks/D2nGpDRe.js" rel="modulepreload"/>
<link crossorigin="" href="https://s.ltrbxd.com/static/js/es/chunks/vCWiOUpe.js" rel="modulepreload"/>
<link crossorigin="" href="https://s.ltrbxd.com/static/js/es/chunks/C-GAFnFO.js" rel="modulepreload"/>
<link crossorigin="" href="https://s.ltrbxd.com/static/js/es/chunks/B2KKeOnX.js" rel="modulepreload"/>
<link crossorigin="" href="https://s.ltrbxd.com/static/js/es/chunks/BKdroH-w.js" rel="modulepreload"/>
<link crossorigin="" href="https://s.ltrbxd.com/static/js/es/chunks/DxtJGFC4.js" rel="modulepreload"/>
<link crossorigin="" href="https://s.ltrbxd.com/static/js/es/chunks/AxRaG6ks.js" rel="modulepreload"/>
<link crossorigin="" href="https://s.ltrbxd.com/static/js/es/chunks/CmVCXTtj.js" rel="modulepreload"/>
<link crossorigin="" href="https://s.ltrbxd.com/static/js/es/chunks/DjoGib27.js" rel="modulepreload"/>
<link crossorigin="" href="https://s.ltrbxd.com/static/js/es/chunks/DHOGRMit.js" rel="modulepreload"/>
<link crossorigin="" href="https://s.ltrbxd.com/static/js/es/chunks/BXwxMPcs.js" rel="modulepreload"/>
<link crossorigin="" href="https://s.ltrbxd.com/static/js/es/chunks/SOgt3rgE.js" rel="modulepreload"/>
<link crossorigin="" href="https://s.ltrbxd.com/static/js/es/chunks/Y-VezM8H.js" rel="modulepreload"/>
<link crossorigin="" href="https://s.ltrbxd.com/static/js/es/chunks/ClnkSUwk.js" rel="modulepreload"/>
<link crossorigin="" href="https://s.ltrbxd.com/static/js/es/chunks/CJ4GRfz7.js" rel="modulepreload"/>
<link crossorigin="" href="https://s.ltrbxd.com/static/js/es/chunks/cYXQUpen.js" rel="modulepreload"/>
<link crossorigin="" href="https://s.ltrbxd.com/static/js/es/chunks/CTIeOcJG.js" rel="modulepreload"/>
<link crossorigin="" href="https://s.ltrbxd.com/static/js/es/chunks/BCi0_APx.js" rel="modulepreload"/>
<link crossorigin="" href="https://s.ltrbxd.com/static/js/es/chunks/DZPCvrkM.js" rel="modulepreload"/>
<link crossorigin="" href="https://s.ltrbxd.com/static/js/es/chunks/CPLialKx.js" rel="modulepreload"/>
<link crossorigin="" href="https://s.ltrbxd.com/static/js/es/chunks/00ixrn22.js" rel="modulepreload"/>
<link crossorigin="" href="https://s.ltrbxd.com/static/js/es/chunks/B9fb8Bne.js" rel="modulepreload"/>
<link crossorigin="" href="https://s.ltrbxd.com/static/js/es/chunks/C0D7dfi8.js" rel="modulepreload"/>
<link crossorigin="" href="https://s.ltrbxd.com/static/js/es/chunks/CfqgOErV.js" rel="modulepreload"/>
<link crossorigin="" href="https://s.ltrbxd.com/static/js/es/chunks/BhibFcxs.js" rel="modulepreload"/>
<link crossorigin="" href="https://s.ltrbxd.com/static/js/es/chunks/DSbtELx8.js" rel="modulepreload"/>
<link crossorigin="" href="https://s.ltrbxd.com/static/js/es/chunks/RTvrqW77.js" rel="modulepreload"/>
<link crossorigin="" href="https://s.ltrbxd.com/static/js/es/chunks/gsj6l96C.js" rel="modulepreload"/>
<link crossorigin="" href="https://s.ltrbxd.com/static/js/es/chunks/DfE0rO6x.js" rel="modulepreload"/>
<link crossorigin="" href="https://s.ltrbxd.com/static/js/es/chunks/BGHdALLu.js" rel="modulepreload"/>
<link crossorigin="" href="https://s.ltrbxd.com/static/js/es/chunks/DfiKuLCj.js" rel="modulepreload"/>
<link crossorigin="" href="https://s.ltrbxd.com/static/js/es/chunks/C58HWxXR.js" rel="modulepreload"/>
<link crossorigin="" href="https://s.ltrbxd.com/static/js/es/chunks/BjuD2H-f.js" rel="modulepreload"/>
<link crossorigin="" href="https://s.ltrbxd.com/static/js/es/chunks/CjlPRQ_z.js" rel="modulepreload"/>
<link crossorigin="" href="https://s.ltrbxd.com/static/js/es/chunks/CdoukE8b.js" rel="modulepreload"/>
<link crossorigin="" href="https://s.ltrbxd.com/static/js/es/chunks/Bwjt9Zt3.js" rel="modulepreload"/>
<link crossorigin="" href="https://s.ltrbxd.com/static/js/es/chunks/CdWFUnCK.js" rel="modulepreload"/>
<link crossorigin="" href="https://s.ltrbxd.com/static/js/es/chunks/DHupp3cl.js" rel="modulepreload"/>
<link crossorigin="" href="https://s.ltrbxd.com/static/js/es/chunks/Cn2TDeu2.js" rel="modulepreload"/>
<link crossorigin="" href="https://s.ltrbxd.com/static/js/es/chunks/Dy-E0KiV.js" rel="modulepreload"/>
<link crossorigin="" href="https://s.ltrbxd.com/static/js/es/chunks/D3y6LkFj.js" rel="modulepreload"/>
<link crossorigin="" href="https://s.ltrbxd.com/static/js/es/chunks/D0CRiLCf.js" rel="modulepreload"/>
<link crossorigin="" href="https://s.ltrbxd.com/static/js/es/chunks/_O9HB_fC.js" rel="modulepreload"/>
<link crossorigin="" href="https://s.ltrbxd.com/static/js/es/chunks/B8N5NSw2.js" rel="modulepreload"/>
<link crossorigin="" href="https://s.ltrbxd.com/static/js/es/chunks/qjl1DJEE.js" rel="modulepreload"/>
<link crossorigin="" href="https://s.ltrbxd.com/static/js/es/chunks/C3wRZFjC.js" rel="modulepreload"/>
<link crossorigin="" href="https://s.ltrbxd.com/static/js/es/chunks/DO__q7rP.js" rel="modulepreload"/>
<link crossorigin="" href="https://s.ltrbxd.com/static/js/es/chunks/BkXYvmP0.js" rel="modulepreload"/>
<link crossorigin="" href="https://s.ltrbxd.com/static/js/es/chunks/CkEEJX_R.js" rel="modulepreload"/>
<link crossorigin="" href="https://s.ltrbxd.com/static/css/base-modal-BOfAec-R.css" rel="stylesheet"/>
<link crossorigin="" href="https://s.ltrbxd.com/static/css/production-masthead-SSTlXlot.css" rel="stylesheet"/>

In [84]:
genres = [
    a.text.strip()
    for a in soup_link.select('a.text-slug[href^="/films/genre/"]')
]
genres

['Drama', 'History']

In [42]:
soup_link.select('a.text-slug[href^="/films/genre/"]')

[<a class="text-slug" href="/films/genre/drama/">Drama</a>,
 <a class="text-slug" href="/films/genre/history/">History</a>]

In [43]:
soup_link.select('a[href$="ratings/"]')

[]

In [36]:
soup_link.find_all('a', class_="text-slug")

[<a class="text-slug tooltip" href="/actor/cillian-murphy/" title="J. Robert Oppenheimer">Cillian Murphy</a>,
 <a class="text-slug tooltip" href="/actor/emily-blunt/" title="Kitty Oppenheimer">Emily Blunt</a>,
 <a class="text-slug tooltip" href="/actor/matt-damon/" title="Leslie Groves">Matt Damon</a>,
 <a class="text-slug tooltip" href="/actor/robert-downey-jr/" title="Lewis Strauss">Robert Downey Jr.</a>,
 <a class="text-slug tooltip" href="/actor/florence-pugh/" title="Jean Tatlock">Florence Pugh</a>,
 <a class="text-slug tooltip" href="/actor/josh-hartnett/" title="Ernest Lawrence">Josh Hartnett</a>,
 <a class="text-slug tooltip" href="/actor/casey-affleck/" title="Boris Pash">Casey Affleck</a>,
 <a class="text-slug tooltip" href="/actor/rami-malek/" title="David Hill">Rami Malek</a>,
 <a class="text-slug tooltip" href="/actor/kenneth-branagh/" title="Niels Bohr">Kenneth Branagh</a>,
 <a class="text-slug tooltip" href="/actor/benny-safdie/" title="Edward Teller">Benny Safdie</a>,
 <a class="text-slug tooltip" href="/actor/jason-clarke/" title="Roger Robb">Jason Clarke</a>,
 <a class="text-slug tooltip" href="/actor/dylan-arnold/" title="Frank Oppenheimer">Dylan Arnold</a>,
 <a class="text-slug tooltip" href="/actor/tom-conti/" title="Albert Einstein">Tom Conti</a>,
 <a class="text-slug tooltip" href="/actor/james-darcy/" title="Patrick Blackett">James D'Arcy</a>,
 <a class="text-slug tooltip" href="/actor/david-dastmalchian/" title="William Borden">David Dastmalchian</a>,
 <a class="text-slug tooltip" href="/actor/dane-dehaan/" title="Kenneth Nichols">Dane DeHaan</a>,
 <a class="text-slug tooltip" href="/actor/alden-ehrenreich/" title="Senate Aide">Alden Ehrenreich</a>,
 <a class="text-slug tooltip" href="/actor/tony-goldwyn/" title="Gordon Gray">Tony Goldwyn</a>,
 <a class="text-slug tooltip" href="/actor/jefferson-hall/" title="Haakon Chevalier">Jefferson Hall</a>,
 <a class="text-slug tooltip" href="/actor/david-krumholtz/" title="Isidor Rabi">David Krumholtz</a>,
 <a class="text-slug tooltip" href="/actor/matthew-modine/" title="Vannevar Bush">Matthew Modine</a>,
 <a class="text-slug tooltip" href="/actor/scott-grimes/" title="Counsel">Scott Grimes</a>,
 <a class="text-slug tooltip" href="/actor/kurt-koehler/" title="Thomas Morgan">Kurt Koehler</a>,
 <a class="text-slug tooltip" href="/actor/john-gowans/" title="Ward Evans">John Gowans</a>,
 <a class="text-slug tooltip" href="/actor/macon-blair/" title="Lloyd Garrison">Macon Blair</a>,
 <a class="text-slug tooltip" href="/actor/harry-groener/" title="Senator McGee">Harry Groener</a>,
 <a class="text-slug tooltip" href="/actor/gregory-jbara/" title="Chairman Magnuson">Gregory Jbara</a>,
 <a class="text-slug tooltip" href="/actor/ted-king-2/" title="Senator Bartlett">Ted King</a>,
 <a class="text-slug tooltip" href="/actor/tim-dekay/" title="Senator Pastore">Tim DeKay</a>,
 <a class="text-slug" id="has-cast-overflow">Show All…</a>,
 <a class="text-slug tooltip" href="/actor/steven-houska/" title="Senator Scott">Steven Houska</a>,
 <a class="text-slug tooltip" href="/actor/petrie-willink/" title="Dutch Student">Petrie Willink</a>,
 <a class="text-slug tooltip" href="/actor/matthias-schweighofer/" title="Werner Heisenberg">Matthias Schweighöfer</a>,
 <a class="text-slug tooltip" href="/actor/alex-wolff/" title="Luis Alvarez">Alex Wolff</a>,
 <a class="text-slug tooltip" href="/actor/josh-zuckerman/" title="Rossi Lomanitz">Josh Zuckerman</a>,
 <a class="text-slug tooltip" href="/actor/rory-keane/" title="Hartland Snyder">Rory Keane</a>,
 <a class="text-slug tooltip" href="/actor/michael-angarano/" title="Robert Serber">Michael Angarano</a>,
 <a class="text-slug tooltip" href="/actor/emma-dumont/" title="Jackie Oppenheimer">Emma Dumont</a>,
 <a class="text-slug tooltip" href="/actor/sadie-stratton/" title="Mary Washburn">Sadie Stratton</a>,
 <a class="text-slug tooltip" href="/actor/britt-kyle/" title="Barbara Chevalier">Britt Kyle</a>,
 <a class="text-slug tooltip" href="/actor/guy-burnet/" title="George Eltenton">Guy Burnet</a>,
 <a class="text-slug tooltip" href="/actor/tom-jenkins-5/" title="Richard Tolman">Tom Jenkins</a>,
 <a class="text-slug tooltip" href="/actor/louise-lombard/" title="Ruth Tolman">Louise Lombard</a>,
 <a class="text-slug tooltip" href="/actor/michael-andrew-baker/" title="Joe Volpe">Michael Andrew Baker</a>,
 <a class="text-slug tooltip" href="/actor/jeff-hephner/" title="Congressman">Jeff Hephner</a>,
 <a class="text-slug tooltip" href="/actor/olli-haaskivi/" title="Edward Condon">Olli Haaskivi</a>,
 <a class="text-slug tooltip" href="/actor/david-rysdahl/" title="Donald Hornig">David Rysdahl</a>,
 <a class="text-slug tooltip" href="/actor/josh-peck/" title="Kenneth Bainbridge">Josh Peck</a>,
 <a class="text-slug tooltip" href="/actor/jack-quaid/" title="Richard Feynman">Jack Quaid</a>,
 <a class="text-slug tooltip" href="/actor/brett-delbuono/" title="Concerned Scientist">Brett DelBuono</a>,
 <a class="text-slug tooltip" href="/actor/gustaf-skarsgard/" title="Hans Bethe">Gustaf Skarsgård</a>,
 <a class="text-slug tooltip" href="/actor/james-urbaniak/" title="Kurt Gödel">James Urbaniak</a>,
 <a class="text-slug tooltip" href="/actor/trond-fausa-aurvag/" title="George Kistiakowsky">Trond Fausa Aurvåg</a>,
 <a class="text-slug tooltip" href="/actor/devon-bostick/" title="Seth Neddermeyer">Devon Bostick</a>,
 <a class="text-slug tooltip" href="/actor/danny-deferrari/" title="Enrico Fermi">Danny Deferrari</a>,
 <a class="text-slug tooltip" href="/actor/christopher-denham/" title="Klaus Fuchs">Christopher Denham</a>,
 <a class="text-slug tooltip" href="/actor/jessica-erin-martin-1/" title="Charlotte Serber">Jessica Erin Martin</a>,
 <a class="text-slug tooltip" href="/actor/ronald-auguste/" title="J. Ernest Wilkins">Ronald Auguste</a>,
 <a class="text-slug tooltip" href="/actor/mate-haumann/" title="Leo Szilard">Máté Haumann</a>,
 <a class="text-slug tooltip" href="/actor/olivia-thirlby/" title="Lilli Hornig">Olivia Thirlby</a>,
 <a class="text-slug tooltip" href="/actor/jack-cutmore-scott/" title="Lyall Johnson">Jack Cutmore-Scott</a>,
 <a class="text-slug tooltip" href="/actor/harrison-gilbertson/" title="Philip Morrison">Harrison Gilbertson</a>,
 <a class="text-slug tooltip" href="/actor/james-remar/" title="Henry Stimson">James Remar</a>,
 <a class="text-slug tooltip" href="/actor/will-roberts/" title="George C. Marshall">Will Roberts</a>,
 <a class="text-slug tooltip" href="/actor/pat-skipper/" title="James Byrnes">Pat Skipper</a>,
 <a class="text-slug tooltip" href="/actor/steve-coulter/" title="James Conant">Steve Coulter</a>,
 <a class="text-slug tooltip" href="/actor/jeremy-john-wells/" title="AAF Officer">Jeremy John Wells</a>,
 <a class="text-slug tooltip" href="/actor/sean-avery/" title="Weatherman">Sean Avery</a>,
 <a class="text-slug tooltip" href="/actor/adam-kroeger/" title="Army Captain">Adam Kroeger</a>,
 <a class="text-slug tooltip" href="/actor/drew-kenney/" title="Soldier">Drew Kenney</a>,
 <a class="text-slug tooltip" href="/actor/bryce-johnson/" title="AAF Officer 2">Bryce Johnson</a>,
 <a class="text-slug tooltip" href="/actor/flora-nolan/" title="Burn Victim">Flora Nolan</a>,
 <a class="text-slug tooltip" href="/actor/kerry-westcott/" title="Laughing Woman">Kerry Westcott</a>,
 <a class="text-slug tooltip" href="/actor/christina-hogue/" title="Kissing Woman">Christina Hogue</a>,
 <a class="text-slug tooltip" href="/actor/clay-bunker/" title="Kissing Man">Clay Bunker</a>,
 <a class="text-slug tooltip" href="/actor/tyler-beardsley/" title="Weeping Man">Tyler Beardsley</a>,
 <a class="text-slug tooltip" href="/actor/maria-teresa-zuppetta/" title="Consoling Woman">Maria Teresa Zuppetta</a>,
 <a class="text-slug tooltip" href="/actor/kate-french-1/" title="Presidential Aide">Kate French</a>,
 <a class="text-slug tooltip" href="/actor/gary-oldman/" title="Harry Truman">Gary Oldman</a>,
 <a class="text-slug tooltip" href="/actor/hap-lawrence/" title="Lyndon Johnson">Hap Lawrence</a>,
 <a class="text-slug tooltip" href="/actor/meg-schimelpfenig/" title="Senator's Assistant (uncredited)">Meg Schimelpfenig</a>,
 <a class="text-slug" href="/director/christopher-nolan/">Christopher Nolan</a>,
 <a class="text-slug" href="/producer/christopher-nolan/">Christopher Nolan</a>,
 <a class="text-slug" href="/producer/emma-thomas-1/">Emma Thomas</a>,
 <a class="text-slug" href="/producer/charles-roven/">Charles Roven</a>,
 <a class="text-slug" href="/producer/andy-thompson/">Andy Thompson</a>,
 <a class="text-slug" href="/writer/christopher-nolan/">Christopher Nolan</a>,
 <a class="text-slug" href="/original-writer/kai-bird/">Kai Bird</a>,
 <a class="text-slug" href="/original-writer/martin-j-sherwin/">Martin J. Sherwin</a>,
 <a class="text-slug" href="/casting/john-papsidera/">John Papsidera</a>,
 <a class="text-slug" href="/editor/jennifer-lame/">Jennifer Lame</a>,
 <a class="text-slug" href="/cinematography/hoyte-van-hoytema/">Hoyte van Hoytema</a>,
 <a class="text-slug" href="/assistant-director/dixon-mcphillips/">Dixon McPhillips</a>,
 <a class="text-slug" href="/assistant-director/nilo-otero/">Nilo Otero</a>,
 <a class="text-slug" href="/assistant-director/andrew-stahl/">Andrew Stahl</a>,
 <a class="text-slug" href="/executive-producer/thomas-hayslip/">Thomas Hayslip</a>,
 <a class="text-slug" href="/executive-producer/james-woods/">James Woods</a>,
 <a class="text-slug" href="/executive-producer/j-david-wargo/">J. David Wargo</a>,
 <a class="text-slug" href="/lighting/giovanni-zelko/">Giovanni Zelko</a>,
 <a class="text-slug" href="/lighting/leigh-mierke/">Leigh Mierke</a>,
 <a class="text-slug" href="/lighting/jacob-bogatin/">Jacob Bogatin</a>,
 <a class="text-slug" href="/lighting/r-adam-chambers/">R. Adam Chambers</a>,
 <a class="text-slug" href="/additional-photography/simon-firsht/">Simon Firsht</a>,
 <a class="text-slug" href="/production-design/ruth-de-jong/">Ruth De Jong</a>,
 <a class="text-slug" href="/art-direction/robert-aguirre/">Robert Aguirre</a>,
 <a class="text-slug" href="/art-direction/roxy-hua/">Roxy Hua</a>,
 <a class="text-slug" href="/art-direction/jake-cavallo/">Jake Cavallo</a>,
 <a class="text-slug" href="/art-direction/samantha-englender/">Samantha Englender</a>,
 <a class="text-slug" href="/set-decoration/andrew-w-bofinger/">Andrew W. Bofinger</a>,
 <a class="text-slug" href="/set-decoration/noelle-king/">Noelle King</a>,
 <a class="text-slug" href="/set-decoration/easton-michael-smith/">Easton Michael Smith</a>,
 <a class="text-slug" href="/set-decoration/adam-willis/">Adam Willis</a>,
 <a class="text-slug" href="/set-decoration/tammy-s-lee/">Tammy S. Lee</a>,
 <a class="text-slug" href="/set-decoration/justin-oneal-miller/">Justin O'Neal Miller</a>,
 <a class="text-slug" href="/set-decoration/jim-hewitt/">Jim Hewitt</a>,
 <a class="text-slug" href="/set-decoration/geoff-dillow-1/">Geoff Dillow</a>,
 <a class="text-slug" href="/set-decoration/susanne-mueller/">Susanne Mueller</a>,
 <a class="text-slug" href="/set-decoration/michael-thurman/">Michael Thurman</a>,
 <a class="text-slug" href="/set-decoration/amy-wallenberg/">Amy Wallenberg</a>,
 <a class="text-slug" href="/set-decoration/scott-b-schmidt/">Scott b Schmidt</a>,
 <a class="text-slug" href="/set-decoration/anthony-whitman/">Anthony Whitman</a>,
 <a class="text-slug" href="/set-decoration/michael-timman/">Michael Timman</a>,
 <a class="text-slug" href="/set-decoration/claire-kaufman/">Claire Kaufman</a>,
 <a class="text-slug" href="/set-decoration/chris-larsen-2/">Chris Larsen</a>,
 <a class="text-slug" href="/special-effects/laurie-pellard/">Laurie Pellard</a>,
 <a class="text-slug" href="/visual-effects/andrew-jackson-5/">Andrew Jackson</a>,
 <a class="text-slug" href="/visual-effects/mike-duffy/">Mike Duffy</a>,
 <a class="text-slug" href="/visual-effects/mike-chambers/">Mike Chambers</a>,
 <a class="text-slug" href="/visual-effects/giacomo-mineo/">Giacomo Mineo</a>,
 <a class="text-slug" href="/stunts/george-cottle/">George Cottle</a>,
 <a class="text-slug" href="/stunts/terry-jackson/">Terry Jackson</a>,
 <a class="text-slug" href="/stunts/mark-norby/">Mark Norby</a>,
 <a class="text-slug" href="/stunts/steve-decastro/">Steve DeCastro</a>,
 <a class="text-slug" href="/stunts/danny-downey/">Danny Downey</a>,
 <a class="text-slug" href="/stunts/nick-larocca/">Nick LaRocca</a>,
 <a class="text-slug" href="/stunts/josh-lakatos/">Josh Lakatos</a>,
 <a class="text-slug" href="/stunts/derek-lacasa/">Derek Lacasa</a>,
 <a class="text-slug" href="/stunts/dean-bailey/">Dean Bailey</a>,
 <a class="text-slug" href="/stunts/jolene-van-vugt-1/">Jolene Van Vugt</a>,
 <a class="text-slug" href="/stunts/duffy-gaver/">Duffy Gaver</a>,
 <a class="text-slug" href="/stunts/tamara-brock-1/">Tamara Brock</a>,
 <a class="text-slug" href="/composer/ludwig-goransson/">Ludwig Göransson</a>,
 <a class="text-slug" href="/sound/alex-gibson/">Alex Gibson</a>,
 <a class="text-slug" href="/sound/richard-king-2/">Richard King</a>,
 <a class="text-slug" href="/sound/willie-d-burton/">Willie D. Burton</a>,
 <a class="text-slug" href="/sound/dan-oconnell/">Dan O'Connell</a>,
 <a class="text-slug" href="/sound/christopher-flick/">Christopher Flick</a>,
 <a class="text-slug" href="/sound/kevin-oconnell-1/">Kevin O'Connell</a>,
 <a class="text-slug" href="/sound/gary-rizzo/">Gary Rizzo</a>,
 <a class="text-slug" href="/costume-design/ellen-mirojnick/">Ellen Mirojnick</a>,
 <a class="text-slug" href="/makeup/christy-falco/">Christy Falco</a>,
 <a class="text-slug" href="/makeup/andrea-steele/">Andrea Steele</a>,
 <a class="text-slug" href="/makeup/luisa-abel/">Luisa Abel</a>,
 <a class="text-slug" href="/makeup/kerrin-jackson/">Kerrin Jackson</a>,
 <a class="text-slug" href="/makeup/jason-hamer/">Jason Hamer</a>,
 <a class="text-slug" href="/hairstyling/heidi-m-baca/">Heidi M. Baca</a>,
 <a class="text-slug" href="/hairstyling/ahou-mofid/">Ahou Mofid</a>,
 <a class="text-slug" href="/hairstyling/lydia-fantini/">Lydia Fantini</a>,
 <a class="text-slug" href="/hairstyling/jaime-leigh-mcintosh/">Jaime Leigh McIntosh</a>,
 <a class="text-slug" href="/hairstyling/jennifer-tremont/">Jennifer Tremont</a>,
 <a class="text-slug" href="/hairstyling/danielle-vigil/">Danielle Vigil</a>,
 <a class="text-slug" href="/studio/syncopy/">Syncopy</a>,
 <a class="text-slug" href="/studio/universal-pictures/">Universal Pictures</a>,
 <a class="text-slug" href="/studio/atlas-entertainment/">Atlas Entertainment</a>,
 <a class="text-slug" href="/studio/breakheart-films/">Breakheart Films</a>,
 <a class="text-slug" href="/studio/peters-creek-entertainment/">Peters Creek Entertainment</a>,
 <a class="text-slug" href="/films/country/uk/"> UK </a>,
 <a class="text-slug" href="/films/country/usa/"> USA </a>,
 <a class="text-slug" href="/films/language/english/">English</a>,
 <a class="text-slug" href="/films/language/dutch/">Dutch</a>,
 <a class="text-slug" href="/films/language/english/">English</a>,
 <a class="text-slug" href="/films/genre/drama/">Drama</a>,
 <a class="text-slug" href="/films/genre/history/">History</a>,
 <a class="text-slug" href="/films/theme/humanity-and-the-world-around-us/by/best-match/">Humanity and the world around us</a>,
 <a class="text-slug" href="/films/theme/politics-and-human-rights/by/best-match/">Politics and human rights</a>,
 <a class="text-slug" href="/films/theme/epic-history-and-literature/by/best-match/">Epic history and literature</a>,
 <a class="text-slug" href="/films/mini-theme/death-symbolism-philosophical-thought-provoking-surreal/by/best-match/">Surreal and thought-provoking visions of life and death</a>,
 <a class="text-slug" href="/films/mini-theme/terrorism-thriller-gripping-intense-political/by/best-match/">Intense political and terrorist thrillers</a>,
 <a class="text-slug" href="/films/mini-theme/powerful-complexity-intellectual-poetic-emotional/by/best-match/">Powerful poetic and passionate drama</a>,
 <a class="text-slug" href="/films/mini-theme/destruction-disaster-scientific-mankind-scientist/by/best-match/">Dangerous technology and the apocalypse</a>,
 <a class="text-slug" href="/films/mini-theme/politician-assassination-democracy-president-compelling/by/best-match/">Riveting political and presidential drama</a>,
 <a class="text-slug" href="/film/oppenheimer-2023/themes/">Show All…</a>]

In [35]:
soup_link.find_all('a', class_='tooltip display-rating -highlight')

[]

In [62]:
soup_link.find_all("meta")

[<meta charset="utf-8"/>,
 <meta content="width=1024" name="viewport"/>,
 <meta content="IE=edge,chrome=1" http-equiv="X-UA-Compatible"/>,
 <meta content="The story of J. Robert Oppenheimer's role in the development of the atomic bomb during World War II." name="description"/>,
 <meta content="video.movie" property="og:type"/>,
 <meta content="https://letterboxd.com/film/oppenheimer-2023/genres/" property="og:url"/>,
 <meta content="Oppenheimer (2023)" property="og:title"/>,
 <meta content="The story of J. Robert Oppenheimer's role in the development of the atomic bomb during World War II." property="og:description"/>,
 <meta content="https://a.ltrbxd.com/resized/sm/upload/mn/uu/op/02/oppenheimer-2023-1200-1200-675-675-crop-000000.jpg?v=aa1b3a6d85" property="og:image"/>,
 <meta content="1200" property="og:image:width"/>,
 <meta content="675" property="og:image:height"/>,
 <meta content="173683136069040" property="fb:app_id"/>,
 <meta content="summary_large_image" name="twitter:card"/>,
 <meta content="@letterboxd" name="twitter:site"/>,
 <meta content="https://letterboxd.com/film/oppenheimer-2023/genres/" name="twitter:url"/>,
 <meta content="Oppenheimer (2023)" name="twitter:title"/>,
 <meta content="The story of J. Robert Oppenheimer's role in the development of the atomic bomb during World War II." name="twitter:description"/>,
 <meta content="Directed by" name="twitter:label1"/>,
 <meta content="Christopher Nolan" name="twitter:data1"/>,
 <meta content="Average rating" name="twitter:label2"/>,
 <meta content="4.17 out of 5" name="twitter:data2"/>,
 <meta content="https://a.ltrbxd.com/resized/sm/upload/mn/uu/op/02/oppenheimer-2023-1200-1200-675-675-crop-000000.jpg?v=aa1b3a6d85" name="twitter:image"/>,
 <meta content="Letterboxd" name="application-name"/>,
 <meta content="#14181C" name="theme-color"/>,
 <meta content="#445566" name="msapplication-TileColor"/>,
 <meta content="app-id=1054271011, affiliate-data=11l5KW, app-argument=https://letterboxd.com/film/oppenheimer-2023/genres/" name="apple-itunes-app"/>,
 <meta content="yes" name="mobile-web-app-capable"/>]

In [56]:
soup_link.find_all("meta", attrs={"name": "twitter:data2"})[0]["content"]

'4.17 out of 5'

In [57]:
float(soup_link.find_all("meta", attrs={"name": "twitter:data2"})[0]["content"].split(' ')[0])

4.17

In [46]:
soup_link.title

In [60]:
for a in soup_link.select('a.text-slug[href^="/films/genre/"]'):
    print(a.text.strip())

Drama
History

In [66]:
soup_link.find_all("meta", attrs={"name": "twitter:data1"})[0]['content']

'Christopher Nolan'

In [123]:
def find_features(soup_genre_link):
    avg_rating = float(soup_genre_link.find_all("meta", attrs={"name": "twitter:data2"})[0]["content"].split(' ')[0])
    genres = [a.text.strip() for a in soup_genre_link.select('a.text-slug[href^="/films/genre/"]')]
    director = soup_genre_link.find_all("meta", attrs={"name": "twitter:data1"})[0]["content"]
    countries = [a.text.strip() for a in soup_genre_link.select('a.text-slug[href^="/films/country/"]')]
    languages = [a.text.strip() for a in soup_genre_link.select('a.text-slug[href^="/films/language/"]')]

    return avg_rating, genres, director, countries, languages

find_features(soup_link)

(4.17,
 ['Drama', 'History'],
 'Christopher Nolan',
 ['UK', 'USA'],
 ['English', 'Dutch', 'English'])